# Generated by Django 6.0.3 on 2026-03-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_user_options_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="app/avatars/%Y/%m/%d/"
            ),
        ),
    ]
