# Generated by Django 6.0.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="platform_role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador da plataforma"),
                    ("member", "Membro"),
                ],
                default="member",
                max_length=20,
            ),
        ),
    ]
