# Generated by Django 6.0.3 on 2026-04-03 21:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _seed_default_templates(apps, schema_editor):
    Workspace = apps.get_model("app", "Workspace")
    TimeEntryTemplate = apps.get_model("app", "TimeEntryTemplate")
    rows = []
    for ws in Workspace.objects.all():
        if TimeEntryTemplate.objects.filter(workspace_id=ws.pk).exists():
            continue
        rows.extend(
            [
                TimeEntryTemplate(
                    workspace_id=ws.pk,
                    name="Simple",
                    use_client=False,
                    use_project=False,
                    use_task=False,
                    use_type=False,
                    use_description=False,
                ),
                TimeEntryTemplate(
                    workspace_id=ws.pk,
                    name="Operational",
                    use_client=True,
                    use_project=True,
                    use_task=True,
                    use_type=False,
                    use_description=False,
                ),
                TimeEntryTemplate(
                    workspace_id=ws.pk,
                    name="Professional",
                    use_client=True,
                    use_project=True,
                    use_task=True,
                    use_type=True,
                    use_description=True,
                ),
            ]
        )
    if rows:
        TimeEntryTemplate.objects.bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_user_platform_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="app.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "ordering": ["name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=6)),
                ("client", models.CharField(blank=True, max_length=255)),
                ("project", models.CharField(blank=True, max_length=255)),
                ("task", models.CharField(blank=True, max_length=255)),
                (
                    "entry_type",
                    models.CharField(
                        blank=True,
                        choices=[("internal", "Interno"), ("external", "Externo")],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="app.department",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="app.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apontamento",
                "verbose_name_plural": "Apontamentos",
                "ordering": ["-date", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="TimeEntryTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("use_client", models.BooleanField(default=False)),
                ("use_project", models.BooleanField(default=False)),
                ("use_task", models.BooleanField(default=False)),
                ("use_type", models.BooleanField(default=False)),
                ("use_description", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entry_templates",
                        to="app.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de apontamento",
                "verbose_name_plural": "Templates de apontamento",
                "ordering": ["name", "pk"],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departments",
                to="app.timeentrytemplate",
            ),
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "working_days",
                    models.JSONField(
                        default=list,
                        help_text='Lista de chaves: "mon","tue","wed","thu","fri","sat","sun"',
                    ),
                ),
                (
                    "expected_hours_per_day",
                    models.PositiveSmallIntegerField(
                        default=8,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                ("has_fixed_days", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_schedules",
                        to="app.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expediente",
                "verbose_name_plural": "Expedientes",
                "ordering": ["name", "pk"],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departments",
                to="app.workschedule",
            ),
        ),
        migrations.CreateModel(
            name="UserDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="app.department",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_departments",
                        to="app.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Departamento do usuário",
                "verbose_name_plural": "Departamentos dos usuários",
                "unique_together": {("user", "workspace")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("workspace", "name")},
        ),
        migrations.RunPython(_seed_default_templates, migrations.RunPython.noop),
    ]
