# Generated by Django 6.0.3 on 2026-03-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_user_avatar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workspace",
            old_name="description",
            new_name="workspace_description",
        ),
        migrations.RenameField(
            model_name="workspace",
            old_name="name",
            new_name="workspace_name",
        ),
        migrations.AddField(
            model_name="workspace",
            name="workspace_avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="app/images/workspaces/avatars/%Y/%m/%d/",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="app/images/users/avatars/%Y/%m/%d/"
            ),
        ),
    ]
