# Generated by Django 6.0.3 on 2026-03-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_description_workspace_workspace_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="workspace_avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="app/images/workspaces/%Y/%m/%d/"
            ),
        ),
    ]
