# Generated by Django 6.0.3 on 2026-04-13 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_client_project_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='card_expiry_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='card_expiry_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='card_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
                ('holder_name', models.CharField(blank=True, max_length=255)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('expiry_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expiry_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cpf_masked', models.CharField(blank=True, max_length=32)),
                ('plan', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
