# Generated by Django 4.2.7 on 2026-04-15 03:07

from django.db import migrations, models


def forwards_backfill_entry_mode(apps, schema_editor):
    TimeEntry = apps.get_model("app", "TimeEntry")
    TimeEntry.objects.filter(
        start_time__isnull=False,
        end_time__isnull=False,
    ).update(entry_mode="time_range")


def reverse_backfill_entry_mode(apps, schema_editor):
    TimeEntry = apps.get_model("app", "TimeEntry")
    TimeEntry.objects.filter(entry_mode="time_range").update(entry_mode="duration")


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_userdepartment_unique_together_client_budget_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="can_delete_time_entries",
            field=models.BooleanField(
                default=True,
                help_text="Se falso, membros não devem excluir apontamentos (regra de aplicação na view).",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="can_edit_time_entries",
            field=models.BooleanField(
                default=True,
                help_text="Se falso, membros não devem editar apontamentos salvos (regra de aplicação na view).",
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="entry_mode",
            field=models.CharField(
                choices=[
                    ("duration", "Duração"),
                    ("time_range", "Intervalo"),
                    ("timer", "Cronômetro"),
                ],
                default="duration",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="status",
            field=models.CharField(
                choices=[("draft", "Rascunho"), ("saved", "Salvo")],
                default="saved",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="timer_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Início do cronômetro (rascunho em andamento ou referência ao salvar).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="time_tracking_mode",
            field=models.CharField(
                choices=[
                    ("duration", "Duração"),
                    ("time_range", "Intervalo"),
                    ("timer", "Cronômetro"),
                ],
                default="duration",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            forwards_backfill_entry_mode,
            reverse_backfill_entry_mode,
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["user", "workspace", "status"],
                name="app_timeent_user_id_8bc5c5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="timeentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "draft")),
                fields=("user", "workspace"),
                name="app_timeentry_one_draft_per_user_workspace",
            ),
        ),
    ]
