# Generated by Django 4.2.7 on 2026-04-15 15:30

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def _mk_check_constraint(*, predicate, name):
    try:
        return models.CheckConstraint(condition=predicate, name=name)
    except TypeError:
        return models.CheckConstraint(check=predicate, name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_time_entry_flow_and_department_flags"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("on_leave", "Afastado"),
                            ("terminated", "Desligado"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("hire_date", models.DateField()),
                ("termination_date", models.DateField(blank=True, null=True)),
                (
                    "current_job_title",
                    models.CharField(
                        blank=True,
                        help_text="Cargo atual para leitura rápida sem depender apenas de histórico.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vínculo do colaborador",
                "verbose_name_plural": "Vínculos dos colaboradores",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                blank=True,
                help_text="Data de nascimento global da pessoa (não depende de workspace).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="platform_join_date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                help_text="Data de entrada na plataforma (diferente de created_at técnico).",
            ),
        ),
        migrations.CreateModel(
            name="JobHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_history_entries",
                        to="app.employeeprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de cargo",
                "verbose_name_plural": "Históricos de cargo",
                "ordering": ["-start_date", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_profiles",
                to="app.workspace",
            ),
        ),
        migrations.CreateModel(
            name="CompensationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "compensation_type",
                    models.CharField(
                        choices=[("monthly", "Mensal"), ("hourly", "Por hora")],
                        max_length=20,
                    ),
                ),
                (
                    "monthly_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compensation_history_entries",
                        to="app.employeeprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de remuneração",
                "verbose_name_plural": "Históricos de remuneração",
                "ordering": ["-start_date", "-pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="jobhistory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("end_date__isnull", True)),
                fields=("employee_profile",),
                name="app_jobhistory_single_current_job_per_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobhistory",
            constraint=_mk_check_constraint(
                predicate=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="app_jobhistory_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeprofile",
            constraint=models.UniqueConstraint(
                fields=("user", "workspace"),
                name="app_employeeprofile_user_workspace_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeprofile",
            constraint=_mk_check_constraint(
                predicate=models.Q(
                    ("termination_date__isnull", True),
                    ("termination_date__gte", models.F("hire_date")),
                    _connector="OR",
                ),
                name="app_employeeprofile_termination_after_hire",
            ),
        ),
        migrations.AddConstraint(
            model_name="compensationhistory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("end_date__isnull", True)),
                fields=("employee_profile",),
                name="app_compensationhistory_single_current_compensation_per_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="compensationhistory",
            constraint=_mk_check_constraint(
                predicate=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="app_compensationhistory_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="compensationhistory",
            constraint=_mk_check_constraint(
                predicate=models.Q(
                    models.Q(
                        ("compensation_type", "monthly"),
                        ("monthly_salary__isnull", False),
                        ("hourly_rate__isnull", True),
                    ),
                    models.Q(
                        ("compensation_type", "hourly"),
                        ("hourly_rate__isnull", False),
                        ("monthly_salary__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="app_compensationhistory_fields_by_type",
            ),
        ),
    ]
