# Generated by Django 6.0.3 on 2026-04-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_employeeprofile_user_birth_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeentry",
            name="is_overtime",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o apontamento é hora extra (opcional no lançamento).",
            ),
        ),
    ]
