# Generated by Django 4.2.7 on 2026-04-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_timeentry_is_overtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeentry",
            name="timer_pending_template_completion",
            field=models.BooleanField(
                default=False,
                help_text="Após parar o cronômetro: indica que o registro salvo ainda aguarda 'Salvar dados do apontamento' ou descarte explícito.",
            ),
        ),
    ]
