# Generated by Django 4.2.7 on 2026-04-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_timeentry_timer_pending_template_completion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workschedule",
            name="has_fixed_days",
            field=models.BooleanField(
                default=True,
                help_text="Se ativado, o expediente usa os dias da semana escolhidos de forma fixa.",
                verbose_name="Folga Fixa",
            ),
        ),
    ]
