# Generated by Django 4.2.7 on 2026-04-18 21:44

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_workschedule_has_fixed_days_verbose"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspace",
            name="budget_total",
        ),
        migrations.CreateModel(
            name="BudgetGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minimum_target_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("minimum_target_date", models.DateField()),
                (
                    "desired_target_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("desired_target_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_goals",
                        to="app.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_budget_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_goals",
                        to="app.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_budget_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_goals",
                        to="app.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta de budget",
                "verbose_name_plural": "Metas de budget",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="FinancialEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_kind",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("time_entry_cost", "Custo de apontamento"),
                            ("reversal", "Estorno"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "flow_type",
                    models.CharField(
                        choices=[("inflow", "Entrada"), ("outflow", "Saída")],
                        max_length=16,
                    ),
                ),
                (
                    "occurred_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("description", models.TextField()),
                (
                    "source_time_entry_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_entries",
                        to="app.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_financial_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_entries",
                        to="app.project",
                    ),
                ),
                (
                    "reversal_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversal_entries",
                        to="app.financialentry",
                    ),
                ),
                (
                    "time_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_entries",
                        to="app.timeentry",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_financial_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_entries",
                        to="app.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lançamento financeiro",
                "verbose_name_plural": "Lançamentos financeiros",
                "ordering": ["-occurred_on", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "occurred_on"],
                        name="app_financi_workspa_74a0d9_idx",
                    ),
                    models.Index(
                        fields=["workspace", "flow_type"],
                        name="app_financi_workspa_5e4018_idx",
                    ),
                    models.Index(
                        fields=["workspace", "entry_kind"],
                        name="app_financi_workspa_444c0b_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="financialentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("time_entry__isnull", False)),
                fields=("time_entry", "entry_kind"),
                name="app_financialentry_unique_kind_per_time_entry",
            ),
        ),
        migrations.AddConstraint(
            model_name="financialentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reversal_of__isnull", False)),
                fields=("reversal_of",),
                name="app_financialentry_single_reversal_per_entry",
            ),
        ),
        migrations.AddIndex(
            model_name="budgetgoal",
            index=models.Index(
                fields=["workspace", "minimum_target_date"],
                name="app_budgetg_workspa_efa3b4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="budgetgoal",
            index=models.Index(
                fields=["workspace", "desired_target_date"],
                name="app_budgetg_workspa_38c624_idx",
            ),
        ),
    ]
