# Generated by Django 4.2.7 on 2026-04-20 19:32

from decimal import Decimal

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def forwards_set_monthly_fixed_flag(apps, schema_editor):
    CompensationHistory = apps.get_model("app", "CompensationHistory")
    CompensationHistory.objects.filter(compensation_type="monthly").update(monthly_salary_is_fixed=True)


def forwards_backfill_time_entry_pay_snapshots(apps, schema_editor):
    from app.compensation_pay import compute_and_assign_pay_snapshots

    TimeEntry = apps.get_model("app", "TimeEntry")

    qs = TimeEntry.objects.filter(status="saved").select_related(
        "user", "workspace", "department", "department__schedule"
    )
    for entry in qs.iterator(chunk_size=200):
        try:
            compute_and_assign_pay_snapshots(entry)
            TimeEntry.objects.filter(pk=entry.pk).update(
                pay_amount_snapshot=entry.pay_amount_snapshot,
                effective_hourly_rate_snapshot=entry.effective_hourly_rate_snapshot,
                expected_month_hours_snapshot=entry.expected_month_hours_snapshot,
                compensation_history_snapshot_id=entry.compensation_history_snapshot_id,
            )
        except Exception:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_workspace_budget_total_budgetgoal_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="compensationhistory",
            name="app_compensationhistory_fields_by_type",
        ),
        migrations.AddField(
            model_name="compensationhistory",
            name="monthly_reference_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Somente para mensal não fixo: base mensal de horas para calcular o valor-hora (ex.: 160).",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="compensationhistory",
            name="monthly_salary_is_fixed",
            field=models.BooleanField(
                blank=True,
                help_text="Somente para tipo mensal: se verdadeiro, o valor-hora deriva do salário e das horas previstas no mês.",
                null=True,
                verbose_name="Salário mensal fixo",
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="compensation_history_snapshot",
            field=models.ForeignKey(
                blank=True,
                help_text="Registro de remuneração usado no cálculo (congelado).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="app.compensationhistory",
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="effective_hourly_rate_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Valor-hora efetivo usado no cálculo (congelado).",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="expected_month_hours_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Horas previstas do mês (fixo) ou horas base contratuais (não fixo) usadas no denominador.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="pay_amount_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor monetário do apontamento congelado no salvamento (remuneração vigente na data).",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.RunPython(forwards_set_monthly_fixed_flag, migrations.RunPython.noop),
        migrations.RunPython(forwards_backfill_time_entry_pay_snapshots, migrations.RunPython.noop),
    ]
