# Generated by Django 4.2.7 on 2026-04-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_compensation_snapshots_and_monthly_rules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentry",
            name="entry_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("internal", "Interno"),
                    ("external", "Externo"),
                    ("displacement", "Deslocamento"),
                    ("home_office", "Home Office"),
                ],
                max_length=24,
            ),
        ),
    ]
