# Generated by Django 4.2.7 on 2026-04-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_timeentry_entry_type_more_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday_public_in_workspace",
            field=models.BooleanField(
                default=False,
                help_text="Se verdadeiro, colegas do mesmo workspace veem dia e mês do aniversário no calendário (sem exibir o ano).",
            ),
        ),
    ]
