# Generated by Django 4.2.7 on 2026-04-22 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_user_birthday_public_in_workspace"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivateBoardColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="private_board_columns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="private_board_columns",
                        to="app.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coluna da lousa privada",
                "verbose_name_plural": "Colunas da lousa privada",
                "ordering": ["workspace", "user", "position", "pk"],
            },
        ),
        migrations.CreateModel(
            name="BoardCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Privado"), ("public", "Público")],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("category", models.CharField(blank=True, max_length=64)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="board_cards",
                        to="app.department",
                    ),
                ),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="board_cards_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "budget_goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="board_cards",
                        to="app.budgetgoal",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="board_cards",
                        to="app.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="board_cards_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "private_column",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="app.privateboardcolumn",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="board_cards",
                        to="app.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="board_cards",
                        to="app.task",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="board_cards_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_cards",
                        to="app.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card do mural",
                "verbose_name_plural": "Cards do mural",
                "ordering": [
                    "workspace",
                    "visibility",
                    "private_column",
                    "position",
                    "pk",
                ],
            },
        ),
        migrations.AddIndex(
            model_name="privateboardcolumn",
            index=models.Index(
                fields=["workspace", "user", "position"],
                name="app_private_workspa_ff892e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="privateboardcolumn",
            constraint=models.UniqueConstraint(
                fields=("workspace", "user", "position"),
                name="app_privateboardcolumn_workspace_user_position_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="boardcard",
            index=models.Index(
                fields=["workspace", "visibility", "position"],
                name="app_boardca_workspa_16890a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="boardcard",
            index=models.Index(
                fields=["private_column", "position"],
                name="app_boardca_private_acd032_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="boardcard",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("private_column__isnull", False), ("visibility", "private")
                    ),
                    models.Q(
                        ("private_column__isnull", True), ("visibility", "public")
                    ),
                    _connector="OR",
                ),
                name="app_boardcard_visibility_private_column_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="boardcard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("visibility", "private")),
                fields=("private_column", "position"),
                name="app_boardcard_private_column_position_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="boardcard",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("private_column__isnull", True), ("visibility", "public")
                ),
                fields=("workspace", "position"),
                name="app_boardcard_public_workspace_position_uniq",
            ),
        ),
    ]
