# Generated by Django 4.2.7 on 2026-04-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_mural_kanban_board_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetgoal",
            name="visibility",
            field=models.CharField(
                choices=[("private", "Privada"), ("public", "Pública")],
                default="private",
                max_length=10,
            ),
        ),
    ]
