# Generated by Django 4.2.7 on 2026-04-23 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _migrate_job_titles_to_roles(apps, schema_editor):
    JobRole = apps.get_model("app", "JobRole")
    EmployeeProfile = apps.get_model("app", "EmployeeProfile")
    JobHistory = apps.get_model("app", "JobHistory")
    db_alias = schema_editor.connection.alias

    cache: dict[tuple[int, str], int] = {}

    def get_or_create_role_id(
        *,
        workspace_id: int | None,
        role_name: str | None,
        created_by_id: int | None = None,
        updated_by_id: int | None = None,
    ) -> int | None:
        if not workspace_id:
            return None
        name = (role_name or "").strip()
        if not name:
            return None
        key = (workspace_id, name)
        cached = cache.get(key)
        if cached is not None:
            return cached
        role, _created = JobRole.objects.using(db_alias).get_or_create(
            workspace_id=workspace_id,
            name=name,
            defaults={
                "description": "",
                "is_active": True,
                "created_by_id": created_by_id,
                "updated_by_id": updated_by_id,
            },
        )
        cache[key] = role.pk
        return role.pk

    for profile in EmployeeProfile.objects.using(db_alias).all().iterator():
        role_id = get_or_create_role_id(
            workspace_id=profile.workspace_id,
            role_name=getattr(profile, "current_job_title", ""),
        )
        if role_id:
            profile.current_job_role_id = role_id
            profile.save(update_fields=["current_job_role"])

    for history in (
        JobHistory.objects.using(db_alias).select_related("employee_profile").all().iterator()
    ):
        role_id = get_or_create_role_id(
            workspace_id=history.employee_profile.workspace_id,
            role_name=getattr(history, "job_title", ""),
        )
        if role_id is None:
            role_id = history.employee_profile.current_job_role_id
        if role_id is None:
            role_id = get_or_create_role_id(
                workspace_id=history.employee_profile.workspace_id,
                role_name="Sem cargo definido",
            )
        history.job_role_id = role_id
        history.save(update_fields=["job_role"])

    for profile in EmployeeProfile.objects.using(db_alias).all().iterator():
        active = (
            JobHistory.objects.using(db_alias)
            .filter(employee_profile_id=profile.pk, end_date__isnull=True)
            .order_by("-start_date", "-pk")
            .first()
        )
        if active is not None and active.job_role_id:
            if profile.current_job_role_id != active.job_role_id:
                profile.current_job_role_id = active.job_role_id
                profile.save(update_fields=["current_job_role"])


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_budgetgoal_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_job_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_job_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_roles",
                        to="app.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
                "ordering": ["name", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="jobrole",
            constraint=models.UniqueConstraint(
                fields=("workspace", "name"),
                name="app_jobrole_workspace_name_uniq",
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="current_job_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_profiles_current",
                to="app.jobrole",
            ),
        ),
        migrations.AddField(
            model_name="jobhistory",
            name="job_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="history_entries",
                to="app.jobrole",
            ),
        ),
        migrations.RunPython(
            _migrate_job_titles_to_roles,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="jobhistory",
            name="job_role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="history_entries",
                to="app.jobrole",
            ),
        ),
        migrations.RemoveField(
            model_name="employeeprofile",
            name="current_job_title",
        ),
        migrations.RemoveField(
            model_name="jobhistory",
            name="job_title",
        ),
    ]
