# Generated by Django 6.0.3 on 2026-04-23 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_mural_status_palette_and_card_colors"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="boardcard",
            name="app_boardca_workspa_16890a_idx",
        ),
        migrations.RenameIndex(
            model_name="boardcard",
            new_name="app_boardca_workspa_4ba53e_idx",
            old_name="app_boardca_ws_vis_lane_pos_idx",
        ),
        migrations.RenameIndex(
            model_name="financialentry",
            new_name="app_financi_workspa_2be316_idx",
            old_name="app_financi_workspa_b0553d_idx",
        ),
        migrations.RenameIndex(
            model_name="muralstatusoption",
            new_name="app_muralst_workspa_5bad08_idx",
            old_name="app_muralstat_ws_pos_idx",
        ),
        migrations.RenameIndex(
            model_name="muralstatusoption",
            new_name="app_muralst_workspa_53de35_idx",
            old_name="app_muralstat_ws_act_pos_idx",
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="current_job_role",
            field=models.ForeignKey(
                blank=True,
                help_text="Cargo atual para leitura rápida (sincronizado com histórico vigente).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_profiles_current",
                to="app.jobrole",
            ),
        ),
    ]
